name: 3. Create Certificates
run-name: Create Certificates (${{ github.ref_name }})

on:
  workflow_call:
    inputs:
      nuke_now:
        type: boolean
        required: false
        default: false
      force_nuke:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      nuke_now:
        description: "Nuke if needed (one-off override)"
        type: boolean
        required: false
        default: false
      force_nuke:
        description: "Force nuke regardless of status"
        type: boolean
        required: false
        default: false

env:
  TEAMID: ${{ secrets.TEAMID }}
  GH_PAT: ${{ secrets.GH_PAT }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
  FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
  FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit

  create_certs:
    name: Certificates
    needs: validate
    runs-on: macos-15
    outputs:
      new_certificate_needed: ${{ steps.set_output.outputs.new_certificate_needed }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Patch Match tables (no sed parens/heredocs)
      - name: Patch Match Tables (safe)
        shell: bash
        run: |
          set -e
          TABLE_PRINTER_PATH="$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb"
          if [ -f "$TABLE_PRINTER_PATH" ]; then
            awk '!/Terminal::Table\.new\(/ {print}' "$TABLE_PRINTER_PATH" > "$TABLE_PRINTER_PATH.tmp"
            mv "$TABLE_PRINTER_PATH.tmp" "$TABLE_PRINTER_PATH"
          else
            echo "table_printer.rb not found"
            exit 1
          fi

      - name: Install Project Dependencies
        shell: bash
        run: bundle install

      - name: Check and create or update Distribution certificate and profiles if needed
        shell: bash
        run: |
          set -e
          echo "Running Fastlane certs lane..."
          bundle exec fastlane certs || true

      - name: Check Distribution certificate and launch Nuke certificates if needed
        id: check_certs
        shell: bash
        run: bundle exec fastlane check_and_renew_certificates

      - name: Set output and annotations based on Fastlane result
        id: set_output
        shell: bash
        env:
          ENABLE_NUKE_CERTS: ${{ vars.ENABLE_NUKE_CERTS }}
          FORCE_NUKE_CERTS: ${{ vars.FORCE_NUKE_CERTS }}
          NUKE_NOW: ${{ inputs.nuke_now }}
          FORCE_NUKE: ${{ inputs.force_nuke }}
        run: |
          set -e
          CERT_STATUS_FILE="$GITHUB_WORKSPACE/fastlane/new_certificate_needed.txt"
          CERT_STATUS="false"
          if [ -f "$CERT_STATUS_FILE" ]; then
            CERT_STATUS="$(tr -d '\r\n' < "$CERT_STATUS_FILE")"
            echo "new_certificate_needed: $CERT_STATUS"
          else
            echo "Certificate status file not found. Defaulting to false."
          fi
          echo "new_certificate_needed=$CERT_STATUS" >> "$GITHUB_OUTPUT"

          # If certs are OK, just inform about automation toggle and exit 0
          if [ "$CERT_STATUS" != "true" ] && [ "${ENABLE_NUKE_CERTS:-}" != "true" ]; then
            echo "::notice::🔔 Automated renewal (nuke) is disabled because ENABLE_NUKE_CERTS is not 'true'."
            exit 0
          fi

          # If certs are bad:
          if [ "$CERT_STATUS" = "true" ]; then
            if [ "${FORCE_NUKE:-}" = "true" ] || [ "${FORCE_NUKE_CERTS:-}" = "true" ] || [ "${ENABLE_NUKE_CERTS:-}" = "true" ] || [ "${NUKE_NOW:-}" = "true" ]; then
              echo "::notice::🧨 A nuke run is authorized (by repo vars or inputs). Proceeding to nuke job."
              exit 0
            else
              echo "::error::❌ No valid distribution certificate found. Automated renewal was skipped because ENABLE_NUKE_CERTS is not 'true' (and no nuke override was provided)."
              echo "::notice::Tip: Re-run with workflow input 'nuke_now=true', or set repo var ENABLE_NUKE_CERTS='true'."
              exit 1
            fi
          fi

  nuke_certs:
    name: Nuke certificates
    needs: [validate, create_certs]
    runs-on: macos-15
    if: ${{ (needs.create_certs.outputs.new_certificate_needed == 'true' && (vars.ENABLE_NUKE_CERTS == 'true' || inputs.nuke_now == 'true')) || vars.FORCE_NUKE_CERTS == 'true' || inputs.force_nuke == 'true' }}
    steps:
      - name: Output from step id 'check_certs'
        shell: bash
        run: echo "new_certificate_needed=${{ needs.create_certs.outputs.new_certificate_needed }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: bundle install

      - name: Run Fastlane nuke_certs
        shell: bash
        run: |
          set -e
          bundle exec fastlane nuke_certs

      - name: Recreate Distribution certificate after nuking
        shell: bash
        run: |
          set -e
          bundle exec fastlane certs

      - name: Add success annotations for nuke and certificate recreation
        if: ${{ success() }}
        shell: bash
        run: |
          echo "::warning::⚠️ All Distribution certificates and TestFlight profiles have been revoked and recreated."
          echo "::warning::❗️ If you have other apps that don't auto-renew, run this workflow for each of those apps."
          echo "::warning::✅ Existing TestFlight builds will keep working."
